[build]
  command = "npm run build:all"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10.9.0"
  YARN_VERSION = "1.22.22"

[env.production]
  [env.production.vars]
    NODE_ENV = "production"
    HUGO_VERSION = "0.156.2"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"